### ISSUE TITLE
Move to MakieOrg?

### ISSUE THREAD

**Issue by juliohm** [eirikbrandsaas/DuBoisPlots.jl#49]
The Makie team is trying to collect all these recipes into a common org for greater visibility:

https://github.com/MakieOrg

Maybe you guys would be open to participate?

cc: @SimonDanisch @jkrumbiegel

ps: nice Julia talk!

**Comment by eirikbrandsaas** [comment]
@juliohm To me that sounds like a good idea!

**Comment by juliohm** [comment]
@eirikbrandsaas any attempt to perform the move?

**Comment by eirikbrandsaas** [comment]
No, not at all. I've been to busy with other stuff and don't have the bandwidth to do this now. Do you know what steps would be required?

**Comment by juliohm** [comment]
Probably just pressing a button on GitHub in the settings tab to transfer
the repository. Then updating the URL in the General registry repository.

Em qua., 28 de jun. de 2023 09:45, Eirik Eylands Brandås <
***@***.***> escreveu:
